### ISSUE TITLE
bug: Heater Shaker API sending the command to open latch while shaking does not behave as expected

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10814]
# Overview
When I send a open latch command to a HS that is shaking, the HS should not open the latch.
The HS does not open the latch but the command does not say forbidden or return an error that the command is not allowed.
Ultimately the command fails.

# Steps to reproduce
[repository](https://github.com/Opentrons/otietalk#setup)
[test `test_open_latch_while_shaking`](https://github.com/Opentrons/otietalk/blob/f6030cc07ce89f32c35998ecbb9d7628ee24937a/tests/hs_test.py#L235)

# Current behavior
command
```js
{'data': {'commandType': 'heaterShaker/openLabwareLatch', 'params': {'moduleId': 'a83c65e79b3713c851b133533757b10ec8cb2d95'}}}
```
response
```js
status_code = 201
POST http://192.168.50.89:31950/runs/8d298990-b457-4a8e-af44-e268dae70923/commands?waitUntilComplete=true&timeout=59000
40.37713 *LONG*{
    "data": {
        "id": "6bcf9004-dc9f-4ad4-a7ff-18928e20b760",
        "createdAt": "2022-06-16T21:11:23.791594+00:00",
        "commandType": "heaterShaker/openLabwareLatch",
        "key": "6bcf9004-dc9f-4ad4-a7ff-18928e20b760",
        "status": "failed",
        "params": {
            "moduleId": "a83c65e79b3713c851b133533757b10ec8cb2d95"
        },
        "error": {
            "id": "1a30c338-8668-4b6a-b065-e3beca2cfbc8",
            "errorType": "UnexpectedProtocolError",
            "createdAt": "2022-06-16T21:12:03.997035+00:00",
            "detail": "/dev/ot_module_heatershaker4: No response to 'M242 \n'"
        },
        "startedAt": "2022-06-16T21:11:23.793690+00:00",
        "completedAt": "2022-06-16T21:12:03.997035+00:00",
        "intent": "setup"
    }
}
```

robot log
```log
Jun 16 21:12:03 kansas opentrons-api-serial[231]: /dev/ot_module_tempdeck5: Read <- b'T:none C:23.998\r\nok\r\nok\r\n'
Jun 16 21:12:03 kansas opentrons-api-serial[231]: /dev/ot_module_heatershaker4: Read <- b'ERR123:main motor:not home (required)\n'
Jun 16 21:12:03 kansas opentrons-api-serial[231]: /dev/ot_module_heatershaker4: retry number 0/0
Jun 16 21:12:03 kansas opentrons-api-serial[231]: /dev/ot_module_heatershaker4: Write -> b'M105 \n'
Jun 16 21:12:03 kansas opentrons-api-serial[231]: /dev/ot_module_heatershaker4: Read <- b'M105 C:24.90 T:None OK\n'
Jun 16 21:12:03 kansas opentrons-api-serial[231]: /dev/ot_module_heatershaker4: Write -> b'M123 \n'
Jun 16 21:12:03 kansas opentrons-api[231]: Execution of 6bcf9004-dc9f-4ad4-a7ff-18928e20b760 failed
                                           Traceback (most recent call last):
                                             File "/usr/lib/python3.7/site-packages/opentrons/protocol_engine/execution/command_executor.py", line 84, in execute
                                               result = await command_impl.execute(command.params)  # type: ignore[arg-type]
                                             File "/usr/lib/python3.7/site-packages/opentrons/protocol_engine/commands/heater_shaker/open_labware_latch.py", line 54, in execute
                                               await hs_hardware_module.open_labware_latch()
                                             File "/usr/lib/python3.7/site-packages/opentrons/hardware_control/thread_manager.py", line 78, in wrapper
                                               return await call_coroutine_threadsafe(loop, attr, *args, **kwargs)
                                             File "/usr/lib/python3.7/site-packages/opentrons/hardware_control/thread_manager.py", line 46, in call_coroutine_threadsafe
                                               return await wrapped
                                             File "/usr/lib/python3.7/site-packages/opentrons/hardware_control/modules/heater_shaker.py", line 436, in open_labware_latch
                                               await self._driver.open_labware_latch()
                                             File "/usr/lib/python3.7/site-packages/opentrons/drivers/heater_shaker/driver.py", line 89, in open_labware_latch
                                               await self._connection.send_command(command=c, retries=DEFAULT_COMMAND_RETRIES)
                                             File "/usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 119, in send_command
                                               data=command.build(), retries=retries, timeout=timeout
                                             File "/usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 140, in send_data
                                               return await self._send_data(data=data, retries=retries)
                                             File "/usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 176, in _send_data
                                               raise NoResponse(port=self._port, command=data)
                                           opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker4: No response to 'M242
                                           '
Jun 16 21:12:03 kansas opentrons-api-serial[231]: /dev/ot_module_heatershaker4: Read <- b'M123 C:402 T:396 OK\n'
Jun 16 21:12:03 kansas opentrons-api-serial[231]: /dev/ot_module_heatershaker4: Write -> b'M241 \n'
Jun 16 21:12:04 kansas uvicorn[231]: INFO:      - "POST /runs/8d298990-b457-4a8e-af44-e268dae70923/commands?waitUntilComplete=true&timeout=59000 HTTP/1.1" 201 Created
Jun 16 21:12:04 kansas opentrons-api-serial[231]: /dev/ot_module_heatershaker4: Read <- b'M241 STATUS:IDLE_CLOSED OK\n
```
# Expected behavior

The command returns immediately telling me it failed and indicates in the error detail it was due to being unable to open the latch when shaking.

**Comment by sanni-t** [comment]
I totally didn't register that this is a protocol engine command! And I haven't yet implemented error raising for this condition in PE 😆🙈
