### ISSUE TITLE
bug: Heater Shaker API set shake speed when the latch is open does not behave as expected

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10813]
# Overview
When I send a shake command to a HS that has a latch not closed, the HS should not shake.
The HS does not shake but the command does not say forbidden or return an error that the command is not allowed.
Ultimately the command fails

# Steps to reproduce
[repository](https://github.com/Opentrons/otietalk#setup)
[test `test_shake_blocked_by_open_latch`](https://github.com/Opentrons/otietalk/blob/f6030cc07ce89f32c35998ecbb9d7628ee24937a/tests/hs_test.py#L207)

# Current behavior
command
```js
{'data': {'commandType': 'heaterShaker/setAndWaitForShakeSpeed', 'params': {'moduleId': 'a83c65e79b3713c851b133533757b10ec8cb2d95', 'rpm': 400}}}
```
response
```js
status_code = 201
POST http://192.168.50.89:31950/runs/1b0e6113-0b3a-4579-a477-79deee6792b8/commands?waitUntilComplete=true&timeout=59000
40.264476 
{
    "data": {
        "id": "cadaff43-abe0-4854-a3e3-7f2562228976",
        "createdAt": "2022-06-16T21:02:34.044774+00:00",
        "commandType": "heaterShaker/setAndWaitForShakeSpeed",
        "key": "cadaff43-abe0-4854-a3e3-7f2562228976",
        "status": "failed",
        "params": {
            "moduleId": "a83c65e79b3713c851b133533757b10ec8cb2d95",
            "rpm": 400.0
        },
        "error": {
            "id": "36c3ddbd-b476-44fd-a8de-a26beebf465f",
            "errorType": "UnexpectedProtocolError",
            "createdAt": "2022-06-16T21:03:14.238014+00:00",
            "detail": "/dev/ot_module_heatershaker4: No response to 'M3 S400 \n'"
        },
        "startedAt": "2022-06-16T21:02:34.047083+00:00",
        "completedAt": "2022-06-16T21:03:14.238014+00:00",
        "intent": "setup"
    }
}
```

robot log
```log
Jun 16 21:03:14 kansas opentrons-api-serial[231]: /dev/ot_module_heatershaker4: Read <- b'ERR126:main motor:plate lock not closed (required)\n'
Jun 16 21:03:14 kansas opentrons-api-serial[231]: /dev/ot_module_heatershaker4: retry number 0/0
Jun 16 21:03:14 kansas opentrons-api-serial[231]: /dev/ot_module_heatershaker4: Write -> b'M105 \n'
Jun 16 21:03:14 kansas opentrons-api[231]: Execution of cadaff43-abe0-4854-a3e3-7f2562228976 failed
                                           Traceback (most recent call last):
                                             File "/usr/lib/python3.7/site-packages/opentrons/protocol_engine/execution/command_executor.py", line 84, in execute
                                               result = await command_impl.execute(command.params)  # type: ignore[arg-type]
                                             File "/usr/lib/python3.7/site-packages/opentrons/protocol_engine/commands/heater_shaker/set_and_wait_for_shake_speed.py", line 63, in execute
                                               await hs_hardware_module.set_speed(rpm=validated_speed)
                                             File "/usr/lib/python3.7/site-packages/opentrons/hardware_control/thread_manager.py", line 78, in wrapper
                                               return await call_coroutine_threadsafe(loop, attr, *args, **kwargs)
                                             File "/usr/lib/python3.7/site-packages/opentrons/hardware_control/thread_manager.py", line 46, in call_coroutine_threadsafe
                                               return await wrapped
                                             File "/usr/lib/python3.7/site-packages/opentrons/hardware_control/modules/heater_shaker.py", line 344, in set_speed
                                               await self._driver.set_rpm(rpm)
                                             File "/usr/lib/python3.7/site-packages/opentrons/drivers/heater_shaker/driver.py", line 132, in set_rpm
                                               await self._connection.send_command(command=c, retries=DEFAULT_COMMAND_RETRIES)
                                             File "/usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 119, in send_command
                                               data=command.build(), retries=retries, timeout=timeout
                                             File "/usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 140, in send_data
                                               return await self._send_data(data=data, retries=retries)
                                             File "/usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 176, in _send_data
                                               raise NoResponse(port=self._port, command=data)
                                           opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker4: No response to 'M3 S400
                                           '
Jun 16 21:03:14 kansas opentrons-api-serial[231]: /dev/ot_module_heatershaker4: Read <- b'M105 C:25.13 T:None OK\n'
```
# Expected behavior

The command returns immediately telling me it failed and indicates in the error detail it was due to being unable to shake when the latch is open.

**Comment by sanni-t** [comment]
See https://github.com/Opentrons/opentrons/issues/10814#issuecomment-1158879843

Fix coming up
