### ISSUE TITLE
Uncaught sqlite3 exception breaks the importing of API

### ISSUE THREAD

**Issue by andySigler** [Opentrons/opentrons#1151]
## overview

An uncaught exception in labware database migration (when a machine is updated to latest `edge`) prevented the API from being imported.

After erasing the database file manually (`rm /data/user_storage/opentrons_data/opentrons.db`), I was then able to import the API, and a database-migrations started. Everything was good after that.

## behavior

After updating a machine to [latest commit](https://github.com/Opentrons/opentrons/commits/d210ab11c8f50ee621dbf51b3d9f5167cf21883f), I am unable to import the API because of an uncaught exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.6/site-packages/opentrons/__init__.py", line 15, in <module>
    database_migration.check_version_and_perform_necessary_migrations()
  File "/usr/local/lib/python3.6/site-packages/opentrons/data_storage/database_migration.py", line 81, in check_version_and_perform_necessary_migrations
    execute_schema_change(conn, create_table_Containers)
  File "/usr/local/lib/python3.6/site-packages/opentrons/data_storage/database_migration.py", line 69, in execute_schema_change
    c.execute(sql_command)
sqlite3.OperationalError: table Containers already exists
```

**Comment by jrodguez** [comment]
I am having the same issue but when I navigate to the opentrons_data folder, there is no pentrons.db to delete.
