### ISSUE TITLE
bug: Polling exception error from tempdeck

### ISSUE THREAD

**Issue by danolson1** [Opentrons/opentrons#12149]
### Overview

I just upgraded my robot software from 5.0.2 to 6.2.1, and now I've started seeing Polling exception errors. Here are a few examples copied from the output of my Jupyter Notebook file.

They're mostly the same, but have some small differences at the end, so I'm posting a few of them.

`[opentrons.hardware_control.poller:_poll_once():87]ERROR: Polling exception
Traceback (most recent call last):
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/poller.py", line 83, in _poll_once
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/modules/tempdeck.py", line 283, in read
  File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 134, in get_temperature
  File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 185, in _send_command
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 136, in send_command
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 170, in send_data
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 190, in _send_data
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/async_serial.py", line 93, in read_until
  File "usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "usr/lib/python3.7/site-packages/serial/serialutil.py", line 663, in read_until
  File "usr/lib/python3.7/site-packages/serial/serialposix.py", line 596, in read
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)`

`[opentrons.hardware_control.poller:_poll_once():87]ERROR: Polling exception
Traceback (most recent call last):
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/poller.py", line 83, in _poll_once
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/modules/tempdeck.py", line 283, in read
  File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 134, in get_temperature
  File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 185, in _send_command
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 136, in send_command
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 170, in send_data
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 190, in _send_data
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/async_serial.py", line 93, in read_until
  File "usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "usr/lib/python3.7/site-packages/serial/serialutil.py", line 663, in read_until
  File "usr/lib/python3.7/site-packages/serial/serialposix.py", line 596, in read
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)`

`[opentrons.hardware_control.poller:_poll_once():87]ERROR: Polling exception
Traceback (most recent call last):
  File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 177, in parse_number
ValueError: could not convert string to float: 'oeC2.5'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/poller.py", line 83, in _poll_once
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/modules/tempdeck.py", line 283, in read
  File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 137, in get_temperature
  File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 62, in parse_temperature_response
  File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 171, in parse_optional_number
  File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 180, in parse_number
opentrons.drivers.utils.ParseError: ParseError(error_message=Unexpected argument to parse_number, parse_source=oeC2.5)`

`[opentrons.hardware_control.poller:_poll_once():87]ERROR: Polling exception
Traceback (most recent call last):
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/poller.py", line 83, in _poll_once
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/modules/tempdeck.py", line 283, in read
  File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 134, in get_temperature
  File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 185, in _send_command
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 136, in send_command
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 170, in send_data
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 190, in _send_data
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/async_serial.py", line 93, in read_until
  File "usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "usr/lib/python3.7/site-packages/serial/serialutil.py", line 663, in read_until
  File "usr/lib/python3.7/site-packages/serial/serialposix.py", line 596, in read
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)`

`[opentrons.hardware_control.poller:_poll_once():87]ERROR: Polling exception
Traceback (most recent call last):
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/poller.py", line 83, in _poll_once
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/modules/tempdeck.py", line 283, in read
  File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 134, in get_temperature
  File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 185, in _send_command
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 136, in send_command
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 170, in send_data
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 190, in _send_data
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/async_serial.py", line 93, in read_until
  File "usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "usr/lib/python3.7/site-packages/serial/serialutil.py", line 663, in read_until
  File "usr/lib/python3.7/site-packages/serial/serialposix.py", line 596, in read
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)`

`[opentrons.hardware_control.poller:_poll_once():87]ERROR: Polling exception
Traceback (most recent call last):
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/poller.py", line 83, in _poll_once
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/modules/tempdeck.py", line 283, in read
  File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 134, in get_temperature
  File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 185, in _send_command
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 136, in send_command
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 170, in send_data
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 190, in _send_data
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/async_serial.py", line 93, in read_until
  File "usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "usr/lib/python3.7/site-packages/serial/serialutil.py", line 663, in read_until
  File "usr/lib/python3.7/site-packages/serial/serialposix.py", line 596, in read
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)`

`[opentrons.hardware_control.poller:_poll_once():87]ERROR: Polling exception
Traceback (most recent call last):
  File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 177, in parse_number
ValueError: could not convert string to float: 'n.853'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/poller.py", line 83, in _poll_once
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/modules/tempdeck.py", line 283, in read
  File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 137, in get_temperature
  File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 62, in parse_temperature_response
  File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 171, in parse_optional_number
  File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 180, in parse_number
opentrons.drivers.utils.ParseError: ParseError(error_message=Unexpected argument to parse_number, parse_source=n.853)`

`[opentrons.hardware_control.poller:_poll_once():87]ERROR: Polling exception
Traceback (most recent call last):
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/poller.py", line 83, in _poll_once
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/modules/tempdeck.py", line 283, in read
  File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 134, in get_temperature
  File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 185, in _send_command
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 136, in send_command
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 170, in send_data
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 190, in _send_data
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/async_serial.py", line 93, in read_until
  File "usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "usr/lib/python3.7/site-packages/serial/serialutil.py", line 663, in read_until
  File "usr/lib/python3.7/site-packages/serial/serialposix.py", line 596, in read
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)`

`[opentrons.hardware_control.poller:_poll_once():87]ERROR: Polling exception
Traceback (most recent call last):
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/poller.py", line 83, in _poll_once
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/modules/tempdeck.py", line 283, in read
  File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 134, in get_temperature
  File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 185, in _send_command
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 136, in send_command
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 170, in send_data
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 209, in _send_data
opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_tempdeck0: No response to 'M105 
'`

`[opentrons.hardware_control.poller:_poll_once():87]ERROR: Polling exception
Traceback (most recent call last):
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/poller.py", line 83, in _poll_once
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/modules/tempdeck.py", line 283, in read
  File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 134, in get_temperature
  File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 185, in _send_command
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 136, in send_command
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 170, in send_data
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py", line 190, in _send_data
  File "usr/lib/python3.7/site-packages/opentrons/drivers/asyncio/communication/async_serial.py", line 93, in read_until
  File "usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "usr/lib/python3.7/site-packages/serial/serialutil.py", line 663, in read_until
  File "usr/lib/python3.7/site-packages/serial/serialposix.py", line 596, in read
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)`

Then when I try to set the temperature of the tempdeck `temp_module.set_temperature(50)`, I get this error message:

`[opentrons.hardware_control.poller:_poll_once():87]ERROR: Polling exception
Traceback (most recent call last):
  File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 62, in parse_temperature_response
KeyError: 'T'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/poller.py", line 83, in _poll_once
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/modules/tempdeck.py", line 283, in read
  File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 137, in get_temperature
  File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 67, in parse_temperature_response
opentrons.drivers.utils.ParseError: ParseError(error_message=Unexpected argument to parse_temperature_response, parse_source=)
KeyError                                  Traceback (most recent call last)
/usr/lib/python3.7/site-packages/opentrons/drivers/utils.pyc in parse_temperature_response(temperature_string, rounding_val)
KeyError: 'T'
During handling of the above exception, another exception occurred:
ParseError                                Traceback (most recent call last)
<ipython-input-20-d25016fe133b> in <module>()
      1 # Note, do not use the %%time magic with the temp module. It causes an error
----> 2 temp_module.set_temperature(50)
/usr/lib/python3.7/site-packages/opentrons/commands/publisher.pyc in _decorated(*args, **kwargs)
/usr/lib/python3.7/site-packages/opentrons/protocols/api_support/util.pyc in _check_version_wrapper(*args, **kwargs)
/usr/lib/python3.7/site-packages/opentrons/protocol_api/module_contexts.pyc in set_temperature(self, celsius)
/usr/lib/python3.7/site-packages/opentrons/protocol_api/core/protocol_api/legacy_module_core.pyc in wait_for_target_temperature(self, celsius)
/usr/lib/python3.7/site-packages/opentrons/hardware_control/adapters.pyc in call_coroutine_sync(loop, to_call, *args, **kwargs)
/usr/lib/python3.7/concurrent/futures/_base.pyc in result(self, timeout)
/usr/lib/python3.7/concurrent/futures/_base.pyc in __get_result(self)
/usr/lib/python3.7/site-packages/opentrons/hardware_control/modules/tempdeck.pyc in await_temperature(self, awaiting_temperature)
/usr/lib/python3.7/site-packages/opentrons/hardware_control/modules/tempdeck.pyc in _await_temperature()
/usr/lib/python3.7/site-packages/opentrons/hardware_control/poller.pyc in wait_next_poll(self)
/usr/lib/python3.7/site-packages/opentrons/hardware_control/poller.pyc in _poll_once(self)
/usr/lib/python3.7/site-packages/opentrons/hardware_control/modules/tempdeck.pyc in read(self)
/usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.pyc in get_temperature(self)
/usr/lib/python3.7/site-packages/opentrons/drivers/utils.pyc in parse_temperature_response(temperature_string, rounding_val)
ParseError: ParseError(error_message=Unexpected argument to parse_temperature_response, parse_source=)`

### Steps to reproduce

Run the attached jupyter notebook.
[AdhE assay setup 2-13-2023.zip](https://github.com/Opentrons/opentrons/files/10734533/AdhE.assay.setup.2-13-2023.zip)

### Current behavior

The protocol still works despite the error messages. 

### Expected behavior

Fix whatever is causing the error messages.

### Operating system

Windows

### System and robot setup or anything else?

This problem only showed up when I upgraded from version 5.0.2 to 6.2.1

**Comment by xiaoxuan1216** [comment]
Probably u should stop the opentrons-robot-server at first.
Go to the home page of the Jupyter notebook and start a new terminal.
> systemctl stop opentrons-robot-server
Then try to restart your procotol. Hopefully it will be useful.
