### ISSUE TITLE
"RuntimeError: generator raised StopIteration" when rows other than the first are used in a distribute()

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#4664]
# Overview

Providing the result of `labware.rows()[n]` where `n != 0` as the destination to a `distribute()` results in an internal exception.

# Steps to reproduce

Simulate this protocol with `opentrons_simulate` or by uploading it to an OT-2.

```
metadata = {"apiLevel":"2.0"}

def run(context):
    tip_rack = context.load_labware("opentrons_96_tiprack_10ul", 1)
    trough = context.load_labware("usascientific_12_reservoir_22ml", 2)
    well_plate = context.load_labware("corning_384_wellplate_112ul_flat", 3)
    pipette = context.load_instrument("p10_multi", mount="right", tip_racks=[tip_rack])
    
    pipette.pick_up_tip()
    
    pipette.distribute(10, trough.wells()[0], well_plate.rows()[0], new_tip="never", disposal_volume=0)
    pipette.distribute(10, trough.wells()[0], well_plate.rows()[1], new_tip="never", disposal_volume=0)
    
    pipette.return_tip()
```

This produces the traceback below.

Note that if the second `distribute()` is commented out, the first succeeds.

Tested on API server v3.15.2.

# Full traceback

```
Traceback (most recent call last):
  File "/Users/maxpm/.pyenv/versions/3.8.0/lib/python3.8/site-packages/opentrons/protocol_api/transfers.py", line 554, in _plan_distribute
    current_xfer = next(plan_iter)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/maxpm/.pyenv/versions/3.8.0/lib/python3.8/site-packages/opentrons/protocol_api/execute.py", line 106, in _run_python
    exec('run(context)', new_globs, new_locs)
  File "<string>", line 1, in <module>
  File "384_plate_filling_apiv2.py", line 13, in run
    pipette.distribute(10, trough.wells()[0], well_plate.rows()[1], new_tip="never", disposal_volume=0)
  File "/Users/maxpm/.pyenv/versions/3.8.0/lib/python3.8/site-packages/opentrons/commands/commands.py", line 595, in decorated
    res = f(*args, **kwargs)
  File "/Users/maxpm/.pyenv/versions/3.8.0/lib/python3.8/site-packages/opentrons/protocol_api/util.py", line 277, in _check_version_wrapper
    return decorated_obj(*args, **kwargs)
  File "/Users/maxpm/.pyenv/versions/3.8.0/lib/python3.8/site-packages/opentrons/protocol_api/contexts.py", line 1426, in distribute
    return self.transfer(volume, source, dest, **kwargs)
  File "/Users/maxpm/.pyenv/versions/3.8.0/lib/python3.8/site-packages/opentrons/commands/commands.py", line 595, in decorated
    res = f(*args, **kwargs)
  File "/Users/maxpm/.pyenv/versions/3.8.0/lib/python3.8/site-packages/opentrons/protocol_api/util.py", line 277, in _check_version_wrapper
    return decorated_obj(*args, **kwargs)
  File "/Users/maxpm/.pyenv/versions/3.8.0/lib/python3.8/site-packages/opentrons/protocol_api/contexts.py", line 1602, in transfer
    self._execute_transfer(plan)
  File "/Users/maxpm/.pyenv/versions/3.8.0/lib/python3.8/site-packages/opentrons/protocol_api/contexts.py", line 1606, in _execute_transfer
    for cmd in plan:
  File "/Users/maxpm/.pyenv/versions/3.8.0/lib/python3.8/site-packages/opentrons/protocol_api/transfers.py", line 422, in __iter__
    yield from {TransferMode.CONSOLIDATE: self._plan_consolidate,
RuntimeError: generator raised StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maxpm/.pyenv/versions/3.8.0/bin/opentrons_simulate", line 10, in <module>
    sys.exit(main())
  File "/Users/maxpm/.pyenv/versions/3.8.0/lib/python3.8/site-packages/opentrons/simulate.py", line 483, in main
    runlog, maybe_bundle = simulate(
  File "/Users/maxpm/.pyenv/versions/3.8.0/lib/python3.8/site-packages/opentrons/simulate.py", line 316, in simulate
    execute.run_protocol(protocol, context)
  File "/Users/maxpm/.pyenv/versions/3.8.0/lib/python3.8/site-packages/opentrons/protocol_api/execute.py", line 126, in run_protocol
    _run_python(protocol, context)
  File "/Users/maxpm/.pyenv/versions/3.8.0/lib/python3.8/site-packages/opentrons/protocol_api/execute.py", line 114, in _run_python
    raise ExceptionInProtocolError(e, tb, str(e), frame.lineno)
opentrons.protocol_api.execute.ExceptionInProtocolError: RuntimeError [line 13]: generator raised StopIteration
```

**Comment by SyntaxColoring** [comment]
The above traceback is from Python 3.8.0.

On Python 3.6.9, this is still broken, but in a different way. Instead of throwing an exception, the run log stops after well B1.

```
Picking up tip from A1 of Opentrons 96 Tip Rack 10 µL on 1
Distributing 10.0 from A1 of USA Scientific 12 Well Reservoir 22 mL on 2 to A1 of Corning 384 Well Plate 112 µL Flat on 3
	Transferring 10.0 from A1 of USA Scientific 12 Well Reservoir 22 mL on 2 to A1 of Corning 384 Well Plate 112 µL Flat on 3
		Aspirating 10.0 uL from A1 of USA Scientific 12 Well Reservoir 22 mL on 2 at 1.0 speed
		Dispensing 10.0 uL into A1 of Corning 384 Well Plate 112 µL Flat on 3 at 1.0 speed
		[snip]
		Aspirating 10.0 uL from A1 of USA Scientific 12 Well Reservoir 22 mL on 2 at 1.0 speed
		Dispensing 10.0 uL into A24 of Corning 384 Well Plate 112 µL Flat on 3 at 1.0 speed
Distributing 10.0 from A1 of USA Scientific 12 Well Reservoir 22 mL on 2 to B1 of Corning 384 Well Plate 112 µL Flat on 3
	Transferring 10.0 from A1 of USA Scientific 12 Well Reservoir 22 mL on 2 to B1 of Corning 384 Well Plate 112 µL Flat on 3
Returning tip
	Dropping tip into A1 of Opentrons 96 Tip Rack 10 µL on 1
```
