### ISSUE TITLE
Depending on installed jsonschema version, opentrons_simulate errors with custom labware

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#5004]
# Overview

The `opentrons` package requirements allow `pip` to install a version of [jsonschema](https://pypi.org/project/jsonschema/) that causes an error when custom labware is used with `opentrons_simulate`.

# Test case

1. `pip install jsonschema==2.6.0`.
2. Extract [CustomLabwareTest.zip](https://github.com/Opentrons/opentrons/files/4205275/CustomLabwareTest.zip) and `cd` to that directory.
3. `opentrons_simulate custom_labware_test.py -L CustomLabware`. It will produce the exception below.
5. `pip install --upgrade jsonschema`. It should install v3.2.0 at the time of writing.
6. Do step 3 again. This time it will succeed.

## Exception on bad jsonschema versions

```
Traceback (most recent call last):
  File "/Users/maxpm/.pyenv/versions/3.6.9/bin/opentrons_simulate", line 8, in <module>
    sys.exit(main())
  File "/Users/maxpm/.pyenv/versions/3.6.9/lib/python3.6/site-packages/opentrons/simulate.py", line 489, in main
    log_level=args.log_level)
  File "/Users/maxpm/.pyenv/versions/3.6.9/lib/python3.6/site-packages/opentrons/simulate.py", line 282, in simulate
    extra_labware = labware_from_paths(custom_labware_paths)
  File "/Users/maxpm/.pyenv/versions/3.6.9/lib/python3.6/site-packages/opentrons/util/entrypoint_util.py", line 30, in labware_from_paths
    defn = labware.verify_definition(child.read_bytes())
  File "/Users/maxpm/.pyenv/versions/3.6.9/lib/python3.6/site-packages/opentrons/protocol_api/labware.py", line 1267, in verify_definition
    jsonschema.validate(to_return, labware_schema_v2)
  File "/Users/maxpm/.pyenv/versions/3.6.9/lib/python3.6/site-packages/jsonschema/validators.py", line 540, in validate
    cls.check_schema(schema)
  File "/Users/maxpm/.pyenv/versions/3.6.9/lib/python3.6/site-packages/jsonschema/validators.py", line 83, in check_schema
    raise SchemaError.create_from(error)
jsonschema.exceptions.SchemaError: {'type': 'object', 'required': ['wells', 'metadata'], 'additionalProperties': False, 'properties': {'wells': {'type': 'array', 'description': 'An array of wells that contain the same metadata', 'items': {'type': 'string'}, 'minItems': 1}, 'metadata': {'type': 'object', 'description': 'Metadata specific to a grid of wells in a labware', 'required': [], 'additionalProperties': False, 'properties': {'displayName': {'type': 'string', 'description': 'User-readable name for the well group'}, 'displayCategory': {'$ref': '#/definitions/displayCategory', 'description': 'Label(s) used in UI to categorize well groups'}, 'wellBottomShape': {'type': 'string', 'description': 'Bottom shape of the well for UI purposes', 'enum': ['flat', 'u', 'v']}}}, 'brand': {'$ref': '#/definitions/brandData', 'description': 'Brand data for the well group (e.g. for tubes)'}}} is not valid under any of the given schemas

Failed validating 'anyOf' in schema['properties']['properties']['additionalProperties']['properties']['items']:
    {'anyOf': [{'$ref': '#'}, {'$ref': '#/definitions/schemaArray'}],
     'default': {}}

On instance['properties']['groups']['items']:
    {'additionalProperties': False,
     'properties': {'brand': {'$ref': '#/definitions/brandData',
                              'description': 'Brand data for the well '
                                             'group (e.g. for tubes)'},
                    'metadata': {'additionalProperties': False,
                                 'description': 'Metadata specific to a '
                                                'grid of wells in a '
                                                'labware',
                                 'properties': {'displayCategory': {'$ref': '#/definitions/displayCategory',
                                                                    'description': 'Label(s) '
                                                                                   'used '
                                                                                   'in '
                                                                                   'UI '
                                                                                   'to '
                                                                                   'categorize '
                                                                                   'well '
                                                                                   'groups'},
                                                'displayName': {'description': 'User-readable '
                                                                               'name '
                                                                               'for '
                                                                               'the '
                                                                               'well '
                                                                               'group',
                                                                'type': 'string'},
                                                'wellBottomShape': {'description': 'Bottom '
                                                                                   'shape '
                                                                                   'of '
                                                                                   'the '
                                                                                   'well '
                                                                                   'for '
                                                                                   'UI '
                                                                                   'purposes',
                                                                    'enum': ['flat',
                                                                             'u',
                                                                             'v'],
                                                                    'type': 'string'}},
                                 'required': [],
                                 'type': 'object'},
                    'wells': {'description': 'An array of wells that '
                                             'contain the same metadata',
                              'items': {'type': 'string'},
                              'minItems': 1,
                              'type': 'array'}},
     'required': ['wells', 'metadata'],
     'type': 'object'}
```

**Comment by sfoster1** [comment]
Good god
