### ISSUE TITLE
Interactive sessions can't load modules

### ISSUE THREAD

**Issue by open3dgenome** [Opentrons/opentrons#5131]
For any given protocol (api 2.0) that works well via the app - the exact same code cannot be ran neither via jupyter notebook, python console (directly on the ot2) nor as a script via `opentrons_execute`.

Example that runs fine on the app:
```
from opentrons import protocol_api

metadata = {'apiLevel' : "2.0"}


def run(protocol: protocol_api.ProtocolContext):
    temp_mod = protocol.load_module('tempdeck', 1)
    tips = protocol.load_labware('opentrons_96_tiprack_300ul', '3')
    pipette = protocol.load_instrument('p300_single', 'right')
    plate = temp_mod.load_labware('corning_96_wellplate_360ul_flat')
    temp_mod.set_temperature(37)

    pipette.pick_up_tip(tips['A1'])

    speeds = [100, 100, 50, 10, 5]
    pipette.aspirate(1, plate['H12'])
    for speed in speeds:
        pipette.flow_rate.aspirate = speed
        pipette.flow_rate.blow_out = speed
        times = 5
        mix_vol = 90
        pipette.mix(times, mix_vol)

    pipette.drop_tip(tips['A1'])
```

When ran inside a notebook, taking care of the context, for example by executing these commands after having imported `import opentrons.execute` and having declared the exact same function `run`:

```
import opentrons.execute
from opentrons import protocol_api

def run(protocol: protocol_api.ProtocolContext):
    temp_mod = protocol.load_module('tempdeck', 1)
    tips = protocol.load_labware('opentrons_96_tiprack_300ul', '3')
    pipette = protocol.load_instrument('p300_single', 'right')
    plate = temp_mod.load_labware('corning_96_wellplate_360ul_flat')
    temp_mod.set_temperature(37)

    pipette.pick_up_tip(tips['A1'])

    speeds = [100, 100, 50, 10, 5]
    pipette.aspirate(1, plate['H12'])
    for speed in speeds:
        pipette.flow_rate.aspirate = speed
        pipette.flow_rate.blow_out = speed
        times = 5
        mix_vol = 90
        pipette.mix(times, mix_vol)

    pipette.drop_tip(tips['A1'])

protocol = opentrons.execute.get_protocol_api('2.0')
run(protocol)
```
The following error appears:

```
                                                   1,1           All
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-33-188722a9411e> in <module>()
      1 protocol = opentrons.execute.get_protocol_api('2.0')
----> 2 run(protocol)  # your protocol will now run

<ipython-input-32-bdd93c796891> in run(protocol)
      5
      6 def run(protocol: protocol_api.ProtocolContext):
----> 7     temp_mod = protocol.load_module('Temperature Module', '1')
      8     tips = protocol.load_labware('opentrons_96_tiprack_300ul', '3')
      9     pipette = protocol.load_instrument('p300_single', 'right')

/usr/lib/python3.7/site-packages/opentrons/protocol_api/util.pyc in _check_version_wrapper(*args, **kwargs)

/usr/lib/python3.7/site-packages/opentrons/protocol_api/protocol_context.pyc in load_module(self, module_name, location)

RuntimeError: Could not find specified module: tempdeck
```

If executed via the console 

```
# opentrons_execute diss.py
Loading json containers...
Json container file load complete, listing database
Found 0 containers to add. Starting migration...
Database migration complete!
Traceback (most recent call last):
  File "usr/lib/python3.7/site-packages/opentrons/protocol_api/execute.py", line 108, in _run_python
  File "<string>", line 1, in <module>
  File "diss.py", line 7, in run
    temp_mod = protocol.load_module('Temperature Module', '1')
  File "usr/lib/python3.7/site-packages/opentrons/protocol_api/util.py", line 289, in _check_version_wrapper
  File "usr/lib/python3.7/site-packages/opentrons/protocol_api/protocol_context.py", line 453, in load_module
RuntimeError: Could not find specified module: tempdeck

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/opentrons_execute", line 11, in <module>
    load_entry_point('opentrons==3.16.1', 'console_scripts', 'opentrons_execute')()
  File "usr/lib/python3.7/site-packages/opentrons/execute.py", line 361, in main
  File "usr/lib/python3.7/site-packages/opentrons/execute.py", line 304, in execute
  File "usr/lib/python3.7/site-packages/opentrons/protocol_api/execute.py", line 131, in run_protocol
  File "usr/lib/python3.7/site-packages/opentrons/protocol_api/execute.py", line 119, in _run_python
opentrons.protocol_api.execute.ExceptionInProtocolError: RuntimeError [line 7]: Could not find specified module: tempdeck
Exception ignored in: <function ProtocolContext.__del__ at 0x751877c8>
Traceback (most recent call last):
  File "usr/lib/python3.7/site-packages/opentrons/protocol_api/protocol_context.py", line 167, in __del__
  File "usr/lib/python3.7/site-packages/opentrons/broker.py", line 50, in unsubscribe
ValueError: list.remove(x): x not in list
Unhandled error in exception handler
context: {'message': 'Task was destroyed but it is pending!', 'task': <Task pending coro=<Controller.watch_modules() running at usr/lib/python3.7/site-packages/opentrons/hardware_control/controller.py:156> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x750ae570>()]>>}
Traceback (most recent call last):
  File "usr/lib/python3.7/asyncio/base_events.py", line 1632, in call_exception_handler
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/util.py", line 10, in _handle_loop_exception
KeyError: 'exception'
Exception ignored in: <coroutine object Controller.watch_modules at 0x74ef4b70>
Traceback (most recent call last):
  File "usr/lib/python3.7/site-packages/opentrons/hardware_control/controller.py", line 156, in watch_modules
  File "usr/lib/python3.7/site-packages/aionotify/base.py", line 93, in setup
  File "usr/lib/python3.7/site-packages/aionotify/aioutils.py", line 139, in stream_from_fd
  File "usr/lib/python3.7/site-packages/aionotify/aioutils.py", line 73, in close
  File "usr/lib/python3.7/site-packages/aionotify/aioutils.py", line 92, in _close
  File "usr/lib/python3.7/asyncio/base_events.py", line 677, in call_soon
  File "usr/lib/python3.7/asyncio/base_events.py", line 469, in _check_closed
RuntimeError: Event loop is closed


```

**Comment by mcous** [comment]
Stale ticket. Modules should work via Jupyter and SSH
