### ISSUE TITLE
bug: Input/output errors are repeatedly logged after removing a Temperature Module

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#5359]
# Overview
After a Temperature Module is removed from an OT-2, the API server will still try to poll it indefinitely, throwing an error on each attempt. The error does not go away after reconnecting the module.

I have no idea if there's a user-facing effect to this, but it's probably not good? It makes logs noisy, at the very least.

Tested on v3.16.1.

# Steps to reproduce
1) SSH in to an OT-2.
2) `journalctl --boot --no-pager --follow --output=short-monotonic`
3) Connect and turn on a Temperature Module. You should see opentrons-api-serial polling for the current temperature once per second.
5) Upload and run this protocol:
    ```python
    metadata = {"apiLevel": "2.2"}
    def run(protocol):
        module = protocol.load_module("Temperature Module", 7)
        module.set_temperature(20)
    ```
6) Let the protocol complete.
7) Turn off the Temperature Module.
8) After a few seconds, you should start to see errors like this:
    ```
    [  283.981680] <serial number> kernel: usb 1-1.3: USB disconnect, device number 7
    [  283.984597] <serial number> kernel: cdc_acm 1-1.3:1.0: failed to set dtr/rts
    [  283.995124] <serial number> opentrons-api[339]: Module Removed: ModuleAtPort(port='/dev/ot_module_tempdeck1', name='tempdeck')
    [  283.997421] <serial number> opentrons-api[339]: Module tempdeck detached from port /dev/ot_module_tempdeck1
    [  292.636349] <serial number> python[339]: Exception in thread Tempdeck recursive update temperature:
    [  292.636349] <serial number> python[339]: Traceback (most recent call last):
    [  292.636349] <serial number> python[339]:   File "/buildroot/output/target/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    [  292.636349] <serial number> python[339]:   File "/buildroot/output/target/usr/lib/python3.7/threading.py", line 865, in run
    [  292.636349] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 285, in _recursive_update_temperature
    [  292.636349] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 250, in _send_command
    [  292.636349] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 269, in _recursive_write_and_return
    [  292.636349] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/serial_communication.py", line111, in write_and_return
    [  292.636349] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/serial_communication.py", line53, in clear_buffer
    [  292.636349] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/serial/serialposix.py", line 595, in reset_input_buffer
    [  292.636349] <serial number> python[339]: termios.error: (5, 'Input/output error')
    [  292.636349] <serial number> python[339]: Exception in thread Tempdeck recursive update temperature:
    [  292.636349] <serial number> python[339]: Traceback (most recent call last):
    [  292.636349] <serial number> python[339]:   File "/buildroot/output/target/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    [  292.636349] <serial number> python[339]:   File "/buildroot/output/target/usr/lib/python3.7/threading.py", line 865, in run
    [  292.636349] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 285, in _recursive_update_temperature
    [  292.636349] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 250, in _send_command
    [  292.636349] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 269, in _recursive_write_and_return
    [  292.636349] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/serial_communication.py", line111, in write_and_return
    [  292.636349] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/serial_communication.py", line53, in clear_buffer
    [  292.636349] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/serial/serialposix.py", line 595, in reset_input_buffer
    [  292.636349] <serial number> python[339]: termios.error: (5, 'Input/output error')
    [  292.636349] <serial number> python[339]: Exception in thread Tempdeck recursive update temperature:
    [  292.643388] <serial number> python[339]: Traceback (most recent call last):
    [  292.643388] <serial number> python[339]:   File "/buildroot/output/target/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    [  292.643388] <serial number> python[339]:   File "/buildroot/output/target/usr/lib/python3.7/threading.py", line 865, in run
    [  292.643388] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 285, in _recursive_update_temperature
    [  292.643388] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 250, in _send_command
    [  292.643388] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 269, in _recursive_write_and_return
    [  292.643388] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/serial_communication.py", line111, in write_and_return
    [  292.643388] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/serial_communication.py", line53, in clear_buffer
    [  292.643388] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/serial/serialposix.py", line 595, in reset_input_buffer
    [  292.643388] <serial number> python[339]: termios.error: (5, 'Input/output error')
    [  292.643388] <serial number> python[339]: Exception in thread Tempdeck recursive update temperature:
    [  292.643388] <serial number> python[339]: Traceback (most recent call last):
    [  292.643388] <serial number> python[339]:   File "/buildroot/output/target/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    [  292.643388] <serial number> python[339]:   File "/buildroot/output/target/usr/lib/python3.7/threading.py", line 865, in run
    [  292.643388] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 285, in _recursive_update_temperature
    [  292.643388] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 250, in _send_command
    [  292.643388] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 269, in _recursive_write_and_return
    [  292.643388] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/serial_communication.py", line111, in write_and_return
    [  292.643388] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/serial_communication.py", line53, in clear_buffer
    [  292.643388] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/serial/serialposix.py", line 595, in reset_input_buffer
    [  292.643388] <serial number> python[339]: termios.error: (5, 'Input/output error')
    [  292.643388] <serial number> python[339]: Exception in thread Tempdeck recursive update temperature:
    [  292.643388] <serial number> python[339]: Traceback (most recent call last):
    [  292.648828] <serial number> python[339]:   File "/buildroot/output/target/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    [  292.648828] <serial number> python[339]:   File "/buildroot/output/target/usr/lib/python3.7/threading.py", line 865, in run
    [  292.648828] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 285, in _recursive_update_temperature
    [  292.648828] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 250, in _send_command
    [  292.648828] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 269, in _recursive_write_and_return
    [  292.648828] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/serial_communication.py", line111, in write_and_return
    [  292.648828] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/serial_communication.py", line53, in clear_buffer
    [  292.648828] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/serial/serialposix.py", line 595, in reset_input_buffer
    [  292.648828] <serial number> python[339]: termios.error: (5, 'Input/output error')
    [  292.648828] <serial number> python[339]: Exception in thread Tempdeck recursive update temperature:
    [  292.648828] <serial number> python[339]: Traceback (most recent call last):
    [  292.648828] <serial number> python[339]:   File "/buildroot/output/target/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    [  292.648828] <serial number> python[339]:   File "/buildroot/output/target/usr/lib/python3.7/threading.py", line 865, in run
    [  292.648828] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 285, in _recursive_update_temperature
    [  292.648828] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 250, in _send_command
    [  292.648828] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 269, in _recursive_write_and_return
    [  292.648828] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/serial_communication.py", line111, in write_and_return
    [  292.648828] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/serial_communication.py", line53, in clear_buffer
    [  292.648828] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/serial/serialposix.py", line 595, in reset_input_buffer
    [  292.648828] <serial number> python[339]: termios.error: (5, 'Input/output error')
    [  292.648828] <serial number> python[339]: Exception in thread Tempdeck recursive update temperature:
    [  292.648828] <serial number> python[339]: Traceback (most recent call last):
    [  292.654254] <serial number> python[339]:   File "/buildroot/output/target/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    [  292.654254] <serial number> python[339]:   File "/buildroot/output/target/usr/lib/python3.7/threading.py", line 865, in run
    [  292.654254] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 285, in _recursive_update_temperature
    [  292.654254] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 250, in _send_command
    [  292.654254] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 269, in _recursive_write_and_return
    [  292.654254] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/serial_communication.py", line111, in write_and_return
    [  292.654254] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/serial_communication.py", line53, in clear_buffer
    [  292.654254] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/serial/serialposix.py", line 595, in reset_input_buffer
    [  292.654254] <serial number> python[339]: termios.error: (5, 'Input/output error')
    [  292.654254] <serial number> python[339]: Exception in thread Tempdeck recursive update temperature:
    [  292.654254] <serial number> python[339]: Traceback (most recent call last):
    [  292.654254] <serial number> python[339]:   File "/buildroot/output/target/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    [  292.654254] <serial number> python[339]:   File "/buildroot/output/target/usr/lib/python3.7/threading.py", line 865, in run
    [  292.654254] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 285, in _recursive_update_temperature
    [  292.654254] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 250, in _send_command
    [  292.654254] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 269, in _recursive_write_and_return
    [  292.654254] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/serial_communication.py", line111, in write_and_return
    [  292.654254] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/serial_communication.py", line53, in clear_buffer
    [  292.654254] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/serial/serialposix.py", line 595, in reset_input_buffer
    [  292.654254] <serial number> python[339]: termios.error: (5, 'Input/output error')
    [  292.654254] <serial number> python[339]: Exception in thread Tempdeck recursive update temperature:
    [  292.654254] <serial number> python[339]: Traceback (most recent call last):
    [  292.659401] <serial number> python[339]:   File "/buildroot/output/target/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    [  292.659401] <serial number> python[339]:   File "/buildroot/output/target/usr/lib/python3.7/threading.py", line 865, in run
    [  292.659401] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 285, in _recursive_update_temperature
    [  292.659401] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 250, in _send_command
    [  292.659401] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 269, in _recursive_write_and_return
    [  292.659401] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/serial_communication.py", line111, in write_and_return
    [  292.659401] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/opentrons/drivers/serial_communication.py", line53, in clear_buffer
    [  292.659401] <serial number> python[339]:   File "usr/lib/python3.7/site-packages/serial/serialposix.py", line 595, in reset_input_buffer
    [  292.659401] <serial number> python[339]: termios.error: (5, 'Input/output error')
    ```
    The errors repeat every 10 seconds or so.
8) Turn the Temperature Module back on. The errors will not go away, but successful temperature polls will be intermixed with them.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535444706) by [Unito](https://www.unito.io/learn-more)

**Comment by SyntaxColoring** [comment]
We think that this should be resolved in v3.17. We should close this ticket when that's confirmed.
