### ISSUE TITLE
bug: GET /networking/status fails response schema validation on some nmcli responses

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#5698]
## overview

On FastAPI, the `GET /networking/status` endpoint will fail response validation and 500 if any enum type in the response dictionary is "wrong". Unfortunately, our ConnectionState enum does not cover all possibilities that `nmcli` may output.

https://github.com/Opentrons/opentrons/blob/7438453a0ae3974ba04aa8b88d0c08c0e09f171b/robot-server/robot_server/service/models/networking.py#L16-L20

## Current behavior

The most common value that our current enum does not cover is `connecting(...)`.

To reproduce, trigger a new Wi-Fi connection and observe that all calls to `GET /networking/status` while the connection is being configured will 500.

## notes

Setting the state field to an enum may be overly optimistic. If we still wanted to d that (as opposed to a string type), the state values appear to be set by nmcli here:

https://github.com/NetworkManager/NetworkManager/blob/f6b1b2401d7412260361e5f4a29921b65e6baf9e/clients/common/nm-client-utils.c#L251-L265

### debug logs

```
May 18 20:21:47 sanni-t20Bot opentrons-api[245]: nmcli --mode multiline --escape no --terse --fields GENERAL.HWADDR,IP4.ADDRESS,IP4.GATEWAY,GENERAL.TYPE,GENERAL.STATE dev show wlan0: stdout=GENERAL.HWADDR:B8:27:EB:E8:D2:A4
                                                 GENERAL.TYPE:wifi
                                                 GENERAL.STATE:50 (connecting (configuring))
May 18 20:21:47 sanni-t20Bot python[245]: DEBUG:    nmcli --mode multiline --escape no --terse --fields GENERAL.HWADDR,IP4.ADDRESS,IP4.GATEWAY,GENERAL.TYPE,GENERAL.STATE dev show wlan0: stdout=GENERAL.HWADDR:B8:27:EB:E8:D2:A4
May 18 20:21:47 sanni-t20Bot python[245]: GENERAL.TYPE:wifi
May 18 20:21:47 sanni-t20Bot python[245]: GENERAL.STATE:50 (connecting (configuring))
May 18 20:21:47 sanni-t20Bot opentrons-api[245]: nmcli --mode multiline --escape no --terse --fields GENERAL.HWADDR,IP4.ADDRESS,IP4.GATEWAY,GENERAL.TYPE,GENERAL.STATE dev show eth0: stdout=GENERAL.HWADDR:B8:27:EB:BD:87:F1
                                                 IP4.ADDRESS[1]:169.254.10.87/16
                                                 IP4.GATEWAY:
                                                 GENERAL.TYPE:ethernet
                                                 GENERAL.STATE:100 (connected)
May 18 20:21:47 sanni-t20Bot python[245]: DEBUG:    nmcli --mode multiline --escape no --terse --fields GENERAL.HWADDR,IP4.ADDRESS,IP4.GATEWAY,GENERAL.TYPE,GENERAL.STATE dev show eth0: stdout=GENERAL.HWADDR:B8:27:EB:BD:87:F1
May 18 20:21:47 sanni-t20Bot python[245]: IP4.ADDRESS[1]:169.254.10.87/16
May 18 20:21:47 sanni-t20Bot python[245]: IP4.GATEWAY:
May 18 20:21:47 sanni-t20Bot python[245]: GENERAL.TYPE:ethernet
May 18 20:21:47 sanni-t20Bot python[245]: GENERAL.STATE:100 (connected)
May 18 20:21:47 sanni-t20Bot opentrons-api[245]: Connectivity: limited
May 18 20:21:47 sanni-t20Bot opentrons-api[245]: Interfaces: {'wlan0': {'ipAddress': None, 'macAddress': 'B8:27:EB:E8:D2:A4', 'gatewayAddress': None, 'state': 'connecting (configuring)', 'type': 'wifi'}, 'eth0': {'ipAddress': '169.254.10.87/16', 'macAddress': 'B8:27:EB:BD:87:F1', 'gatewayAddress': '', 'state': 'connected', 'type': 'ethernet'}}
May 18 20:21:47 sanni-t20Bot opentrons-api[245]: Failed calling nmcli
                                                 Traceback (most recent call last):
                                                   File "usr/lib/python3.7/site-packages/robot_server/service/routers/networking.py", line 38, in get_networking_status
                                                   File "pydantic/main.py", line 283, in pydantic.main.BaseModel.__init__
                                                 pydantic.error_wrappers.ValidationError: 1 validation error for NetworkingStatus
                                                 interfaces -> wlan0 -> state
                                                   value is not a valid enumeration member; permitted: 'connected', 'connecting', 'disconnected', 'unavailable' (type=type_error.enum; enum_values=[<ConnectionState.connected: 'connected'>, <ConnectionState.connecting: 'connecting'>, <ConnectionState.disconnected: 'disconnected'>, <ConnectionState.unavailable: 'unavailable'>])
May 18 20:21:47 sanni-t20Bot opentrons-api[245]: GET /networking/status : 500, 1 validation error for NetworkingStatus
                                                 interfaces -> wlan0 -> state
                                                   value is not a valid enumeration member; permitted: 'connected', 'connecting', 'disconnected', 'unavailable' (type=type_error.enum; enum_values=[<ConnectionState.connected: 'connected'>, <ConnectionState.connecting: 'connecting'>, <ConnectionState.disconnected: 'disconnected'>, <ConnectionState.unavailable: 'unavailable'>])
```

**Comment by amitlissack** [comment]
The only benefit we get from an enum is documenting the possible return strings. I agree with you that this should just be a string.
