### ISSUE TITLE
bug: Single-Channel pipettes can't calibrate labware at the back of the deck

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#6886]
# Overview

Two intertwined problems:

1. Under certain circumstances, during labware calibration, the software will prevent you from jogging the pipette far enough to center it over well A1.
2. In a subset of those circumstances, you additionally won't be able to jog the pipette *at all* when calibrating that labware. 

# Steps to reproduce

1. Attach a P20 Single-Channel. (We don't think it matters which mount, but I tested with the right.)
2. Upload this protocol, and do pipette and labware calibration.
    ```python
    metadata = {'apiLevel': `2.8`}
    def run(protocol):
    tip_rack = protocol.load_labware('opentrons_96_tiprack_20ul', 10)
    pipette = protocol.load_instrument('p20_single_gen2', mount='right', tip_racks=[tip_rack])
    pipette.pick_up_tip()
    pipette.return_tip()
    ```
3. When calibrating the tip rack, try to jog around. You may or may not be able to.
    1. If you *can* jog around, try 0.1 mm jogging as far back as possible, to see how far you could get, if you had to. Note the distance from there to the center of A1—this is how much margin you'd have for an imperfect pipette calibration and imperfect labware (and maybe an imperfect deck calibration?). You may not even be able to reach the center of well A1 at all.
    2. If you *can't* jog around...
        1. Switch the step size to 10 mm.
        2. Jog one step towards the front of the robot. The pipette should move.
        3. You should now be able to jog around as normal.
        4. Switch the step size to 0.1 mm or 1 mm.
        5. Jog as far back as possible, to see how far you could get, as in step 3i, above.

Tested on v3.21.2.

# Current behavior

* During labware calibration, the software blocks you from jogging a Single-Channel pipette far back enough to comfortably center it over well A1 in an Opentrons tip rack in slots 10 or 11.
* Additionally, if the initial labware calibration position happens to be beyond that threshold, none of the jog buttons will work. But you may be able to break the robot out with a 10 mm jog towards the front of the robot.

This seems to be an unfortunate result of the OT-2 helpfully preventing you from jogging out-of-bounds.

From `journalctl`:

```
Oct 29 16:08:45 OT2CEP20190716A09 uvicorn[231]: ERROR:    Out of bounds jog
Oct 29 16:08:45 OT2CEP20190716A09 uvicorn[231]: Traceback (most recent call last):
Oct 29 16:08:45 OT2CEP20190716A09 uvicorn[231]:   File "usr/lib/python3.7/site-packages/opentrons/api/calibration.py", line 243, in jog
Oct 29 16:08:45 OT2CEP20190716A09 uvicorn[231]:   File "usr/lib/python3.7/site-packages/opentrons/hardware_control/adapters.py", line 56, in call_coroutine_sync
Oct 29 16:08:45 OT2CEP20190716A09 uvicorn[231]:   File "usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
Oct 29 16:08:45 OT2CEP20190716A09 uvicorn[231]:   File "usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
Oct 29 16:08:45 OT2CEP20190716A09 uvicorn[231]:   File "usr/lib/python3.7/site-packages/opentrons/hardware_control/api.py", line 959, in move_rel
Oct 29 16:08:45 OT2CEP20190716A09 uvicorn[231]:   File "usr/lib/python3.7/site-packages/opentrons/hardware_control/api.py", line 1093, in _move
Oct 29 16:08:45 OT2CEP20190716A09 uvicorn[231]:   File "usr/lib/python3.7/site-packages/opentrons/hardware_control/util.py", line 93, in check_motion_bounds
Oct 29 16:08:45 OT2CEP20190716A09 uvicorn[231]: opentrons.hardware_control.types.OutOfBoundsMove: OutOfBoundsMove: Out of bounds move: Y=(351.70263198060184 motor controller, 347.93368503257585 deck) too high for limit 350.0
```

With a P20 Single-Channel, well A1 of a tip rack in slot 10 happens to be very close to those bounds—or maybe actually, truly beyond them.

# Expected behavior

* Single-Channel pipettes should be able to comfortably reach well A1 of all standard labware, even when the labware is in the back row.
  * If this is impossible because the pipette really can't be allowed to move that far back...
    * The initial calibration position should be clamped to what is allowed.
    * You should be able to jog around freely from the initial calibration position, except when that jog would move the pipette of bounds.

# See also

* Bug #5551, which makes problems like this a bit harder to diagnose than they could be.
* PR #6565 (merged v3.21.0), which I *suspect* is what turned the underlying geometry problem into the problem where the jog buttons don't do anything. (But I'm not sure.)

**Comment by SyntaxColoring** [comment]
# Workarounds

Try any of these:

* Switch the step size to 10 mm and jog the pipette towards the front of the robot. From there, you should be able to jog around as normal. But the distance you can move it back will be limited. 
* Move your tip rack to somewhere other than the back row.
* Downgrade under robot software v3.21.0.
  * I haven't tested this workaround; see my mention of PR #6565 in the post above.

**Comment by SyntaxColoring** [comment]
The gantry *does* have several mm of extra physical space to jog back, but it's nontrivial for the software to let you use it. Some notes from @sfoster1 on why:

> Well there's the extra annoying thing that the cross gantry can travel farther +y when the head is -x than it can when the head is at its x stop, and in fact can physically go farther +y than its home position when the gantry is in those other positions. but this really really is not a safe thing to do
> 
> [For the software to permit jogging that far back when the head is -x,] we would have to implement a bunch of special case behavior for homing in that situation, and probably carving out a notch in the total area of the gantry for when it would actually trigger the stops
