### ISSUE TITLE
Errors with temperature module

### ISSUE THREAD

**Issue by kappa95** [Opentrons/opentrons#7059]
Hi, we are using 20 OT-2 with their temperature module, very often we experience these error messages when we are executing protocols which involves temperature modules.
Generally we are executing the protocols using `opentrons_execute` command in the terminal of the robot. This in order to execute the protocols externally and automatize the process.

```
Nov 19 14:02:48 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 14:02:52 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 14:03:59 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 14:04:08 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 44, in parse_number_from_substring
                                                  ValueError: could not convert string to float: '5T'
Nov 19 14:10:39 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 14:10:46 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 14:10:52 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 44, in parse_number_from_substring
                                                  ValueError: could not convert string to float: '500C5010\nk\nk\nT'
Nov 19 14:23:58 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_temperature_response: T5.00C55.000
Nov 19 14:25:07 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 14:25:27 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 14:27:23 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 15:14:17 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 15:34:51 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 44, in parse_number_from_substring
                                                  ValueError: could not convert string to float: '55T'
Nov 19 15:34:58 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 15:35:46 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 15:48:44 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 44, in parse_number_from_substring
                                                  ValueError: could not convert string to float: '499\nok\nk\nT5.0'
Nov 19 15:48:46 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 44, in parse_number_from_substring
                                                  ValueError: could not convert string to float: '54.989\r\nT'
Nov 19 15:48:52 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 44, in parse_number_from_substring
                                                  ValueError: could not convert string to float: '55.02T'
Nov 19 15:50:20 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 15:52:48 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 15:54:18 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_temperature_response: 55.000
Nov 19 15:54:18 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 356, in _recursive_update_temperature
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 80, in parse_temperature_response
                                                  opentrons.drivers.utils.ParseError: Unexpected argument to parse_temperature_response: 55.000
                                                  
                                                  During handling of the above exception, another exception occurred:
                                                  
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 44, in parse_number_from_substring
                                                  ValueError: could not convert string to float: '499\nk\nk\nT'
Nov 19 15:54:27 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_temperature_response: .000
Nov 19 15:54:34 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 15:56:25 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 44, in parse_number_from_substring
                                                  ValueError: could not convert string to float: '499\nk\nT'
Nov 19 15:56:36 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 44, in parse_number_from_substring
                                                  ValueError: could not convert string to float: '499\nk\nk\nT'
Nov 19 16:21:48 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 16:21:50 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
                                                  
                                                  During handling of the above exception, another exception occurred:
                                                  
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 356, in _recursive_update_temperature
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 85, in parse_temperature_response
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 85, in <dictcomp>
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 49, in parse_number_from_substring
                                                  opentrons.drivers.utils.ParseError: Unexpected argument to parse_number_from_substring: T55.000
                                                  
                                                  During handling of the above exception, another exception occurred:
                                                  
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 44, in parse_number_from_substring
                                                  ValueError: could not convert string to float: '54.989T'
Nov 19 16:21:53 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 44, in parse_number_from_substring
                                                  ValueError: could not convert string to float: '54T'
Nov 19 16:25:36 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_temperature_response: :500C5010
Nov 19 16:25:37 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 356, in _recursive_update_temperature
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 80, in parse_temperature_response
                                                  opentrons.drivers.utils.ParseError: Unexpected argument to parse_temperature_response: :500C5010
                                                  
                                                  During handling of the above exception, another exception occurred:
                                                  
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 44, in parse_number_from_substring
                                                  ValueError: could not convert string to float: '500\nk\nok\n5.0'
Nov 19 16:25:46 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 16:29:47 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 44, in parse_number_from_substring
                                                  ValueError: could not convert string to float: '499\nk\nk\nT'
Nov 19 16:29:58 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_temperature_response: T:55.0:55.010
Nov 19 16:32:16 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 16:32:18 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_temperature_response: .979
Nov 19 16:32:20 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/temp_deck/driver.py", line 356, in _recursive_update_temperature
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 80, in parse_temperature_response
                                                  opentrons.drivers.utils.ParseError: Unexpected argument to parse_temperature_response: .979
                                                  
                                                  During handling of the above exception, another exception occurred:
                                                  
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 16:37:45 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_temperature_response: 0
Nov 19 17:00:43 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 44, in parse_number_from_substring
                                                  ValueError: could not convert string to float: '55.021\r\nT'
Nov 19 17:00:50 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 17:00:51 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 17:05:01 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_temperature_response: T:55.000C:55.021
Nov 19 17:05:13 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 44, in parse_number_from_substring
                                                  ValueError: could not convert string to float: '55.T'
Nov 19 17:08:43 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 17:09:16 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 44, in parse_number_from_substring
                                                  ValueError: could not convert string to float: '499\nk\nk\nT5.0'
Nov 19 17:12:59 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 17:13:07 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
Nov 19 17:16:39 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 44, in parse_number_from_substring
                                                  ValueError: could not convert string to float: '54.989\r\nT'
Nov 19 17:18:04 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 44, in parse_number_from_substring
                                                  ValueError: could not convert string to float: '500C599\nk\nk\n5.0'
Nov 19 17:18:31 CAL-LAB-OTB05 opentrons-api[258]: Unexpected argument to parse_number_from_substring:
                                                  Traceback (most recent call last):
                                                    File "usr/lib/python3.7/site-packages/opentrons/drivers/utils.py", line 41, in parse_number_from_substring
                                                  IndexError: list index out of range
```

**Comment by mcous** [comment]
Thanks for the report @kappa95! I've transferred the issue over here to Opentrons/opentrons, where the code that is throwing this error lives
