### ISSUE TITLE
bug: update-server responds with HTTP 500 if you try to add an empty SSH key

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#7173]
# Overview

If you try to upload an SSH key of `""` using `POST /server/ssh_keys`, update-server errors internally.

It's easy to accidentally try to upload a key of `""` if you follow [Support's instructions](https://support.opentrons.com/en/articles/3203681-setting-up-ssh-access-to-your-ot-2#3-upload-your-public-key:~:text=3.%20Upload%20your%20public%20key) and the `ot2_ssh_key.pub` file doesn't exist.

# Current behavior

```
% curl \
    -H 'Content-Type: application/json' \
    -d "{\"key\":\"\"}" \
    169.254.57.100:31950/server/ssh_keys

<html><head><title>500 Internal Server Error</title></head><body><h1>500 Internal Server Error</h1>Server got itself in trouble</body></html>
```

## Log excerpt

```
Dec 14 21:03:48 ecf71f opentrons-update[272]: Exception serving POST /server/ssh_keys
                                              Traceback (most recent call last):
                                                File "aiohttp\_helpers.pyx", line 24, in aiohttp._helpers.reify.__get__
                                              KeyError: 'url'
                                              
                                              During handling of the above exception, another exception occurred:
                                              
                                              Traceback (most recent call last):
                                                File "aiohttp\_helpers.pyx", line 24, in aiohttp._helpers.reify.__get__
                                              KeyError: 'host'
                                              
                                              During handling of the above exception, another exception occurred:
                                              
                                              Traceback (most recent call last):
                                                File "usr/lib/python3.7/site-packages/otupdate/buildroot/__init__.py", line 22, in log_error_middleware
                                                File "usr/lib/python3.7/site-packages/otupdate/buildroot/ssh_key_management.py", line 44, in decorated
                                                File "usr/lib/python3.7/site-packages/otupdate/buildroot/ssh_key_management.py", line 126, in add
                                              IndexError: list index out of range
```

# Expected behavior

An HTTP 400-something, since the request was invalid.

**Comment by SyntaxColoring** [comment]
The culprit seems to be:

https://github.com/Opentrons/opentrons/blob/61d9b4feb87f4bb1c2327b404175427a8f8fbb47/update-server/otupdate/buildroot/ssh_key_management.py#L126

If `pubkey` is `""`, `pubkey.split()` will be `[]`.
