### ISSUE TITLE
bug: Threadmanager issue on non-systemd system

### ISSUE THREAD

**Issue by Koeng101** [Opentrons/opentrons#8627]
# Overview
I am encountering a threadmanager error when trying to simulate a protocol on my linux machine. The error is below.

What might be helpful is that during virtual environment setup I get the following error:
```
Collecting systemd-python==234
  Using cached systemd-python-234.tar.gz (53 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/koeng/gits/protocols/venv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nptwneno/systemd-python_167bfe4e01c749fc8665ffb2588937e4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nptwneno/systemd-python_167bfe4e01c749fc8665ffb2588937e4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
egg_info --egg-base /tmp/pip-pip-egg-info-dctvkm6k
         cwd: /tmp/pip-install-nptwneno/systemd-python_167bfe4e01c749fc8665ffb2588937e4/
    Complete output (12 lines):
    Cannot find libsystemd or libsystemd-journal:

    Package libsystemd was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libsystemd.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libsystemd' found

    Package libsystemd-journal was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libsystemd-journal.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libsystemd-journal' found

    ----------------------------------------
```
This makes complete sense since I do not run systemd (I use void linux, rolling updates). Not really sure why systemd is a requirement for opentrons (it really IS infecting everything I guess), but perhaps this could be associated with the error.

Interestingly enough, this is supported by the fact that the protocol simulates perfectly on a Ubuntu machine of mine.

# Steps to reproduce

```
python3 -m venv venv
pip3 install opentrons
opentrons_simulate protocol.py
```

# Current behavior

When I run `opentrons_simulate protocol.py`, I get the following error:
```
opentrons_simulate protocol.py
/home/koeng/.opentrons/robot_settings.json not found. Loading defaults
Exception in Thread Manager build
Traceback (most recent call last):
  File "/home/koeng/gits/protocols/venv/lib/python3.10/site-packages/opentrons/hardware_control/thread_manager.py", line 150, in _build_and_start_loop
    managed_obj = loop.run_until_complete(builder(*args,
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/koeng/gits/protocols/venv/lib/python3.10/site-packages/opentrons/hardware_control/api.py", line 228, in build_hardware_simulator
    api_instance = cls(backend, loop=checked_loop, config=checked_config)
  File "/home/koeng/gits/protocols/venv/lib/python3.10/site-packages/opentrons/hardware_control/api.py", line 79, in __init__
    self._execution_manager = ExecutionManager(loop=loop)
  File "/home/koeng/gits/protocols/venv/lib/python3.10/site-packages/opentrons/hardware_control/execution_manager.py", line 15, in __init__
    self._condition = asyncio.Condition(loop=loop)
  File "/usr/lib/python3.10/asyncio/locks.py", line 230, in __init__
    super().__init__(loop=loop)
  File "/usr/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Condition() since it is no longer necessary
Traceback (most recent call last):
  File "/home/koeng/gits/protocols/venv/bin/opentrons_simulate", line 8, in <module>
    sys.exit(main())
  File "/home/koeng/gits/protocols/venv/lib/python3.10/site-packages/opentrons/simulate.py", line 530, in main
    runlog, maybe_bundle = simulate(
  File "/home/koeng/gits/protocols/venv/lib/python3.10/site-packages/opentrons/simulate.py", line 344, in simulate
    context = get_protocol_api(
  File "/home/koeng/gits/protocols/venv/lib/python3.10/site-packages/opentrons/simulate.py", line 182, in get_protocol_api
    return _build_protocol_context(
  File "/home/koeng/gits/protocols/venv/lib/python3.10/site-packages/opentrons/simulate.py", line 198, in _build_protocol_context
    ctx_impl = ProtocolContextImplementation(
  File "/home/koeng/gits/protocols/venv/lib/python3.10/site-packages/opentrons/protocols/context/protocol_api/protocol_context.py", line 81, in __init__
    self._hw_manager = HardwareManager(hardware)
  File "/home/koeng/gits/protocols/venv/lib/python3.10/site-packages/opentrons/protocols/api_support/util.py", line 314, in __init__
    self._current = ThreadManager(API.build_hardware_simulator).sync
  File "/home/koeng/gits/protocols/venv/lib/python3.10/site-packages/opentrons/hardware_control/thread_manager.py", line 130, in __init__
    object.__getattribute__(self, 'managed_thread_ready_blocking')()
  File "/home/koeng/gits/protocols/venv/lib/python3.10/site-packages/opentrons/hardware_control/thread_manager.py", line 135, in managed_thread_ready_blocking
    raise ThreadManagerException("Failed to create Managed Object")
opentrons.hardware_control.thread_manager.ThreadManagerException: Failed to create Managed Object
```

# Expected behavior
I expect opentrons_simulate to work as advertised (ie, simulate my protocol)

**Comment by Koeng101** [comment]
Awesome, thank you! Weird that python did that. Will use virtual env
