### ISSUE TITLE
bug: Labware Position Check fails when run the second time on a protocol with modules attached

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#8994]
# Steps to reproduce

1. Upload this protocol through the `edge` (currently eaea0656710d8734168cd4ad84b08043783f50c0) robot software and app.

```python
metadata = {
    "apiLevel": "2.11"
}

def run(protocol):
    tc = protocol.load_module("thermocycler")
    well_plate = tc.load_labware("biorad_96_wellplate_200ul_pcr")
    tip_rack = protocol.load_labware("opentrons_96_tiprack_20ul", 2)
    pipette = protocol.load_instrument("p20_single_gen2", mount="right")

    pipette.pick_up_tip(tip_rack.wells()[0])
    pipette.transfer(20, well_plate.wells()[0], well_plate.wells()[1])
    pipette.return_tip()
```

2. Click through Labware Position Check.
3. Try starting Labware Position Check again on the same run.

# Current behavior

I see this in the app:

<img width="802" alt="Screen Shot 2021-12-06 at 4 37 13 PM" src="https://user-images.githubusercontent.com/3236864/144926857-048f8fd3-bc8c-4a55-ae66-2d42d33f0ffb.png">

And this in the server logs:

```
Dec 06 21:37:07 OT2CEP20191023B21 opentrons-api[242]: Execution of 249fdeb0-c326-4e1a-a5d5-16c6652f3d08 failed
                                                      Traceback (most recent call last):
                                                        File "/usr/lib/python3.7/site-packages/opentrons/protocol_engine/execution/command_executor.py", line 73, in execute
                                                          result = await command_impl.execute(command.params)  # type: ignore[arg-type]  # noqa: E501
                                                        File "/usr/lib/python3.7/site-packages/opentrons/protocol_engine/commands/load_module.py", line 76, in execute
                                                          module_id=params.moduleId,
                                                        File "/usr/lib/python3.7/site-packages/opentrons/protocol_engine/execution/equipment.py", line 205, in load_module
                                                          attached_mod_instance = await self._get_hardware_module(model)
                                                        File "/usr/lib/python3.7/site-packages/opentrons/protocol_engine/execution/equipment.py", line 236, in _get_hardware_module
                                                          raise ModuleNotAttachedError("Requested module not found.")
                                                      opentrons.protocol_engine.errors.exceptions.ModuleNotAttachedError: Requested module not found.
```

# Expected behavior

The second Labware Position Check should work the same way as the first one.

**Comment by SyntaxColoring** [comment]
The problem seems to be:

1. The app issues a fresh set of `loadModule` commands every time Labware Position Check is started.
2. And it reuses the same run.

`loadModule` commands aren't idempotent. A successful `loadModule` consumes that module, so subsequent `loadModule` commands won't see it. So the second LPC attempt is failing because no more modules of that type are connected.

-----

Solution paths...

We can't simply make `loadModule` commands reuse a previously-loaded module, because this will break multiples-of-a-module support. If a protocol issues two separate but identical `loadModule` commands, it's important for them resolve into two distinct hardware modules.

Options:

* Change the app so it only loads modules once per run resource, not once per LPC attempt.
* Add a parameter to the `loadModule` command that's an allowlist of module IDs that it may reuse.
* Change the Protocol Engine `loadModule` command so that it reuses modules by default, and also give it a new parameter that's a blocklist of module IDs that it may not reuse. If you, as a Protocol Engine consumer, want multiples of a module, it's your responsibility to set the blocklist equal to the IDs of every module you've already loaded.
* Change the app so it creates a fresh run resource every time LPC is started.

**Comment by SyntaxColoring** [comment]
Interestingly, repeatedly running LPC on this protocol seems to work:

```
metadata = {"apiLevel": "2.11"}

def run(protocol):
    tm1 = protocol.load_module("temperature module", 1)
    tm2 = protocol.load_module("temperature module", 4)
    plate = tm1.load_labware("biorad_96_wellplate_200ul_pcr")
    pipette = protocol.load_instrument("p300_single_gen2", mount="left")
    tip_rack = protocol.load_labware("opentrons_96_tiprack_300ul", 2)
```

I'm not sure why this one would work but not the one in the issue OP.

**Comment by SyntaxColoring** [comment]
We're moving forward with this solution path unless anything comes up:

> Change the loadModule contract and implementation so that it returns a prior-loaded module. For multiples-of-a-module to keep working, it should only do this if the two loads' locations are identical.

Next steps for me:

1. Poke around the code and see at what layer are modules "consumed" when they're loaded. Do we need to be worried about module loads during LPC offsetting module loads in the actual protocol?
2.. Figure out why the Temperature Module repro case above didn't work the way I expected it to.

**Comment by SyntaxColoring** [comment]
3. Think through how module load idempotence interacts with module compatible loading.
